#
# Put the kernel together for various hardware configurations.	3/9/84
#
# Defines:
#	ACA	== include Async. Comm. Adapter (RS-232) driver.
#	PA	== include Printer Adapter driver.
#	FLP	== include Floppy driver.
#	WIN	== include Winchester driver.
#	S_FLP	== system is floppy based.
#	S_WIN	== system is winchester based.
#	SMALL	== use parameters (from param.h) appropiate for a small system.
#
# Makes:
#	venix	== winchester based with floppy driver
#	venix.id == winchester based with floppy driver, split i&d
#	venix.f	== floppy based with winchester driver
#	venix.f.id == floppy based with winchester driver, split i&d
#	venix.fo== floppy based
#
CC	= cc
LD	= ld

venix:		../syslib/syslib.a ../devlib/devlib.a low.o c.o
	$(LD) -x -o venix low.o c.o ../syslib/syslib.a ../devlib/devlib.a
	chmod 444 venix

c.o:	c.c
	$(CC) -DACA -DPA -DFLP -DWIN -DS_WIN -I.. -c c.c

venix.f:	../syslib/syslib.a ../devlib/devlib.a low.o c.f.o
	$(LD) -x -o venix.f low.o c.f.o ../syslib/syslib.a ../devlib/devlib.a
	vstrip venix.f
	chmod 444 venix.f

c.f.o:	c.c
	$(CC) -DACA -DPA -DFLP -DWIN -DS_FLP -I.. -c c.c
	mv c.o c.f.o

venix.id:	../syslib/syslib.a ../devlib/devlib.a low.o c.o
	$(LD) -i -x -o venix.id low.o c.o ../syslib/syslib.a ../devlib/devlib.a
	vstrip venix.id
	chmod 444 venix.id

venix.f.id:	../syslib/syslib.a ../devlib/devlib.a low.o c.f.o
	$(LD) -i -x -o venix.f.id low.o c.f.o ../syslib/syslib.a\
			../devlib/devlib.a
	vstrip venix.f.id
	chmod 444 venix.f.id

venix.fo:	../syslib/syslib.a ../devlib/devlib.a low.o c.fo.o
	$(LD) -x -o venix.fo low.o c.fo.o ../syslib/syslib.a ../devlib/devlib.a
	vstrip venix.fo
	chmod 444 venix.fo

c.fo.o:	c.c
	$(CC) -DACA -DPA -DFLP -DS_FLP -DSMALL -I.. -c c.c
	mv c.o c.fo.o
