_malloc:	push	bp
_malloc+1:	mov	bp,sp
_malloc+3:	push	si
_malloc+4:	push	di
_malloc+5:	push	cx
_malloc+6:	xor	si,si
_malloc+8:	mov	ax,*4(bp)
_malloc+b:	mov	*-6(bp),ax
_malloc+e:	mov	bx,*-6(bp)
_malloc+11:	mov	di,(bx)
_malloc+13:	or	di,di
_malloc+15:	je	_malloc+2d
_malloc+17:	cmp	di,*6(bp)
_malloc+1a:	jb	_malloc+27
_malloc+1c:	or	si,si
_malloc+1e:	je	_malloc+24
_malloc+20:	cmp	di,(si)
_malloc+22:	jnb	_malloc+27
_malloc+24:	mov	si,*-6(bp)
_malloc+27:	add	*-6(bp),*4
_malloc+2b:	j	_malloc+e
_malloc+2d:	or	si,si
_malloc+2f:	je	_malloc+57
_malloc+31:	mov	di,*2(si)
_malloc+34:	mov	ax,*6(bp)
_malloc+37:	add	*2(si),ax
_malloc+3a:	mov	ax,*6(bp)
_malloc+3d:	sub	(si),ax
_malloc+3f:	jne	_malloc+53
_malloc+41:	add	si,*4
_malloc+44:	mov	ax,*2(si)
_malloc+47:	mov	*-2(si),ax
_malloc+4a:	mov	ax,(si)
_malloc+4c:	mov	*-4(si),ax
_malloc+4f:	or	ax,ax
_malloc+51:	jne	_malloc+41
_malloc+53:	mov	ax,di
_malloc+55:	j	_malloc+67
_malloc+57:	cmp	*4(bp),#0
_malloc+5c:	jne	_malloc+65
_malloc+5e:	call	0
_malloc+61:	or	ax,ax
_malloc+63:	jne	_malloc+6
_malloc+65:	xor	ax,ax
_malloc+67:	pop	cx
_malloc+68:	pop	di
_malloc+69:	pop	si
_malloc+6a:	pop	bp
_malloc+6b:	ret
_mfree:
_mfree:		push	bp
_mfree+1:	mov	bp,sp
_mfree+3:	push	si
_mfree+4:	push	di
_mfree+5:	push	cx
_mfree+6:	mov	si,*8(bp)
_mfree+9:	mov	di,*4(bp)
_mfree+c:	cmp	*2(di),si
_mfree+f:	jnbe	_mfree+1b
_mfree+11:	cmp	(di),*0
_mfree+14:	je	_mfree+1b
_mfree+16:	add	di,*4
_mfree+19:	j	_mfree+c
_mfree+1b:	cmp	di,*4(bp)
_mfree+1e:	jbe	_mfree+54
_mfree+20:	mov	ax,*-2(di)
_mfree+23:	add	ax,*-4(di)
_mfree+26:	cmp	ax,si
_mfree+28:	jne	_mfree+54
_mfree+2a:	mov	ax,*6(bp)
_mfree+2d:	add	*-4(di),ax
_mfree+30:	mov	ax,si
_mfree+32:	add	ax,*6(bp)
_mfree+35:	cmp	ax,*2(di)
_mfree+38:	jne	_mfree+6e
_mfree+3a:	mov	ax,(di)
_mfree+3c:	add	*-4(di),ax
_mfree+3f:	cmp	(di),*0
_mfree+42:	je	_mfree+74
_mfree+44:	add	di,*4
_mfree+47:	mov	ax,*2(di)
_mfree+4a:	mov	*-2(di),ax
_mfree+4d:	mov	ax,(di)
_mfree+4f:	mov	*-4(di),ax
_mfree+52:	j	_mfree+3f
_mfree+54:	mov	ax,si
_mfree+56:	add	ax,*6(bp)
_mfree+59:	cmp	ax,*2(di)
_mfree+5c:	jne	_mfree+70
_mfree+5e:	cmp	(di),*0
_mfree+61:	je	_mfree+70
_mfree+63:	mov	ax,*6(bp)
_mfree+66:	sub	*2(di),ax
_mfree+69:	mov	ax,*6(bp)
_mfree+6c:	add	(di),ax
_mfree+6e:	j	_mfree+99
_mfree+70:	cmp	*6(bp),*0
_mfree+74:	je	_mfree+99
_mfree+76:	mov	ax,*2(di)
_mfree+79:	mov	*-6(bp),ax
_mfree+7c:	mov	*2(di),si
_mfree+7f:	mov	si,*-6(bp)
_mfree+82:	mov	ax,(di)
_mfree+84:	mov	*-6(bp),ax
_mfree+87:	mov	ax,*6(bp)
_mfree+8a:	mov	(di),ax
_mfree+8c:	add	di,*4
_mfree+8f:	mov	ax,*-6(bp)
_mfree+92:	mov	*6(bp),ax
_mfree+95:	or	ax,ax
_mfree+97:	jne	_mfree+76
_mfree+99:	pop	cx
_mfree+9a:	pop	di
_mfree+9b:	pop	si
_mfree+9c:	pop	bp
_mfree+9d:	ret
